# NEAREST_FRONTIER 0
# BETTER_FRONTIER 1

r1/explorer:
  ros__parameters:
    use_sim_time: true
    freq: 2.0 # hz

    map_frame: r1/map
    robot_frame: r1/base_link
    odom_frame: r1/odom

    policy: 1
    separation_weight: 0.7
    distance_weight: 0.8

    proximity_threshold: 1.5
    improvement_ratio: 0.4

r2/explorer:
  ros__parameters:
    use_sim_time: true
    freq: 2.0 # hz

    map_frame: r2/map
    robot_frame: r2/base_link
    odom_frame: r2/odom

    policy: 1
    separation_weight: 0.7
    distance_weight: 0.8

    proximity_threshold: 1.5
    improvement_ratio: 0.4

r3/explorer:
  ros__parameters:
    use_sim_time: true
    freq: 2.0 # hz

    map_frame: r3/map
    robot_frame: r3/base_link
    odom_frame: r3/odom

    policy: 1
    separation_weight: 0.7
    distance_weight: 0.8

    proximity_threshold: 1.5
    improvement_ratio: 0.4
