r1/controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [simple]
    simple:
      rt_freq: 30.0 
      plugin: easynav_simple_controller/SimpleController
      max_linear_speed: 1.0
      max_angular_speed: 1.5
      look_ahead_dist: 0.3
      k_rot: 0.8

r1/localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [lazy]
    lazy:
      rt_freq: 50.0
      freq: 5.0
      plugin: easynav_lazy_localizer/LazyLocalizer

r1/maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [costmap, multiplexor, frontier]
    costmap:
      freq: 10.0
      plugin: easynav_costmap_maps_manager/CostmapMapsManager
      filters: [obstacles, inflation]
      obstacles:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/ObstaclesFilter
      inflation:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/InflationFilter
        inflation_radius: 0.5
        cost_scaling_factor: 8.0
        inscribed_radius: 0.05
    multiplexor:
      freq: 10.0
      plugin: easynav_multiplexor_maps_manager/MultiplexorMapsManager
      fixed_map_ns: "r1"
      robot_namespaces: ["r1", "r2", "r3"]
      r1:
        x: 1.5
        y: 0.0
        Y: 0.0
        topic: "maps_manager_node/costmap/incoming_map"
      r2:
        x: -3.5
        y: -2.0
        Y: 0.0
        topic: "maps_manager_node/costmap/incoming_map"
      r3:
        x: 3.5
        y: 3.0
        Y: 0.0
        topic: "maps_manager_node/costmap/incoming_map"
    frontier:
      freq: 10.0
      plugin: easynav_frontier_maps_manager/FrontierMapsManager
      proximity_radius: 0.3
      obstacle_threshold: 10

r1/planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [simple]
    simple:
      freq: 0.5
      plugin: easynav_costmap_planner/CostmapPlanner
      cost_factor: 10.0

r1/sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [laser1]
    perception_default_frame: odom
    laser1:
      topic: scan_raw
      type: sensor_msgs/msg/LaserScan
      group: points
    camera1:
      topic: rgbd_camera/points
      type: sensor_msgs/msg/PointCloud2
      group: points

r1/system_node:
  ros__parameters:
    use_sim_time: true
    use_real_time: false
    position_tolerance: 0.2
    angle_tolerance: 0.5
    tf_prefix: r1



r2/controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [simple]
    simple:
      rt_freq: 30.0 
      plugin: easynav_simple_controller/SimpleController
      max_linear_speed: 1.0
      max_angular_speed: 1.5
      look_ahead_dist: 0.3
      k_rot: 0.8

r2/localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [lazy]
    lazy:
      rt_freq: 50.0
      freq: 5.0
      plugin: easynav_lazy_localizer/LazyLocalizer

r2/maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [costmap, multiplexor, frontier]
    costmap:
      freq: 10.0
      plugin: easynav_costmap_maps_manager/CostmapMapsManager
      filters: [obstacles, inflation]
      obstacles:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/ObstaclesFilter
      inflation:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/InflationFilter
        inflation_radius: 0.5
        cost_scaling_factor: 8.0
        inscribed_radius: 0.05
    multiplexor:
      freq: 10.0
      plugin: easynav_multiplexor_maps_manager/MultiplexorMapsManager
      fixed_map_ns: "r2"
      robot_namespaces: ["r1", "r2", "r3"]
      r1:
        x: 1.5
        y: 0.0
        Y: 0.0
        topic: "maps_manager_node/costmap/incoming_map"
      r2:
        x: -3.5
        y: -2.0
        Y: 0.0
        topic: "maps_manager_node/costmap/incoming_map"
      r3:
        x: 3.5
        y: 3.0
        Y: 0.0
        topic: "maps_manager_node/costmap/incoming_map"
    frontier:
      freq: 10.0
      plugin: easynav_frontier_maps_manager/FrontierMapsManager
      proximity_radius: 0.3
      obstacle_threshold: 10

r2/planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [simple]
    simple:
      freq: 0.5
      plugin: easynav_costmap_planner/CostmapPlanner
      cost_factor: 10.0

r2/sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [laser1]
    perception_default_frame: odom
    laser1:
      topic: scan_raw
      type: sensor_msgs/msg/LaserScan
      group: points
    camera1:
      topic: rgbd_camera/points
      type: sensor_msgs/msg/PointCloud2
      group: points

r2/system_node:
  ros__parameters:
    use_sim_time: true
    use_real_time: false
    position_tolerance: 0.2
    angle_tolerance: 0.5
    tf_prefix: r2




r3/controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [simple]
    simple:
      rt_freq: 30.0 
      plugin: easynav_simple_controller/SimpleController
      max_linear_speed: 1.0
      max_angular_speed: 1.5
      look_ahead_dist: 0.3
      k_rot: 0.8

r3/localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [lazy]
    lazy:
      rt_freq: 50.0
      freq: 5.0
      plugin: easynav_lazy_localizer/LazyLocalizer

r3/maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [costmap, multiplexor, frontier]
    costmap:
      freq: 10.0
      plugin: easynav_costmap_maps_manager/CostmapMapsManager
      filters: [obstacles, inflation]
      obstacles:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/ObstaclesFilter
      inflation:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/InflationFilter
        inflation_radius: 0.5
        cost_scaling_factor: 8.0
        inscribed_radius: 0.05
    multiplexor:
      freq: 10.0
      plugin: easynav_multiplexor_maps_manager/MultiplexorMapsManager
      fixed_map_ns: "r3"
      robot_namespaces: ["r1", "r2", "r3"]
      r1:
        x: 1.5
        y: 0.0
        Y: 0.0
        topic: "maps_manager_node/costmap/incoming_map"
      r2:
        x: -3.5
        y: -2.0
        Y: 0.0
        topic: "maps_manager_node/costmap/incoming_map"
      r3:
        x: 3.5
        y: 3.0
        Y: 0.0
        topic: "maps_manager_node/costmap/incoming_map"
    frontier:
      freq: 10.0
      plugin: easynav_frontier_maps_manager/FrontierMapsManager
      proximity_radius: 0.3
      obstacle_threshold: 10

r3/planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [simple]
    simple:
      freq: 0.5
      plugin: easynav_costmap_planner/CostmapPlanner
      cost_factor: 10.0

r3/sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [laser1]
    perception_default_frame: odom
    laser1:
      topic: scan_raw
      type: sensor_msgs/msg/LaserScan
      group: points
    camera1:
      topic: rgbd_camera/points
      type: sensor_msgs/msg/PointCloud2
      group: points

r3/system_node:
  ros__parameters:
    use_sim_time: true
    use_real_time: false
    position_tolerance: 0.2
    angle_tolerance: 0.5
    tf_prefix: r3

