r1/controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [simple]
    simple:
      rt_freq: 30.0 
      plugin: easynav_simple_controller/SimpleController
      max_linear_speed: 0.35
      max_angular_speed: 0.45
      look_ahead_dist: 0.3
      k_rot: 1.5
      k_p: 1.3
      k_i: 0.0
      k_d: 0.15

r1/localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [lazy]
    lazy:
      rt_freq: 30.0
      freq: 10.0
      plugin: easynav_lazy_localizer/LazyLocalizer

r1/maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [costmap, multiplexor, frontier]
    costmap:
      freq: 10.0
      plugin: easynav_costmap_maps_manager/CostmapMapsManager
      filters: [obstacles, inflation]
      obstacles:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/ObstaclesFilter
      inflation:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/InflationFilter
        inflation_radius: 1.0
        cost_scaling_factor: 8.0
        inscribed_radius: 0.05
    multiplexor:
      freq: 5.0
      plugin: easynav_multiplexor_maps_manager/MultiplexorMapsManager
      fixed_map_ns: "r1"
      robot_namespaces: ["r1", "r2", "r3"]
      r1: {x: 0.0, y: 0.0, Y: 0.0, topic: "local_map"}
      r2: {x: 0.0, y: -3.0, Y: 0.0, topic: "local_map"}
      r3: {x: 0.0, y: 6.0, Y: 0.0, topic: "local_map"}
    frontier:
      freq: 5.0
      plugin: easynav_frontier_maps_manager/FrontierMapsManager
      proximity_radius: 0.4 # Must be greater than system node position tolerance
      obstacle_threshold: 40
      clustering: true
      dbscan_eps_px: 0
      dbscan_min_points: 10

r1/planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [costmap]
    costmap:
      freq: 1.0
      plugin: easynav_costmap_planner/CostmapPlanner
      cost_factor: 10.0

r1/sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [laser1]
    perception_default_frame: odom
    laser1: {topic: scan_raw, type: sensor_msgs/msg/LaserScan}
    camera1: {topic: rgbd_camera/points, type: sensor_msgs/msg/PointCloud2}

r1/system_node:
  ros__parameters:
    use_sim_time: true
    use_real_time: false
    freq: 30.0
    rt_freq: 50.0
    allow_preempt_goal: true
    position_tolerance: 0.4
    angle_tolerance: 1.0
    tf_prefix: r1



r2/controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [simple]
    simple:
      rt_freq: 30.0 
      plugin: easynav_simple_controller/SimpleController
      max_linear_speed: 0.35
      max_angular_speed: 0.45
      look_ahead_dist: 0.3
      k_rot: 1.5
      k_p: 1.3
      k_i: 0.0
      k_d: 0.15

r2/localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [lazy]
    lazy:
      rt_freq: 30.0
      freq: 10.0
      plugin: easynav_lazy_localizer/LazyLocalizer

r2/maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [costmap, multiplexor, frontier]
    costmap:
      freq: 10.0
      plugin: easynav_costmap_maps_manager/CostmapMapsManager
      filters: [obstacles, inflation]
      obstacles:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/ObstaclesFilter
      inflation:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/InflationFilter
        inflation_radius: 1.0
        cost_scaling_factor: 8.0
        inscribed_radius: 0.05
    multiplexor:
      freq: 5.0
      plugin: easynav_multiplexor_maps_manager/MultiplexorMapsManager
      fixed_map_ns: "r2"
      robot_namespaces: ["r1", "r2", "r3"]
      r1: {x: 0.0, y: 0.0, Y: 0.0, topic: "local_map"}
      r2: {x: 0.0, y: -3.0, Y: 0.0, topic: "local_map"}
      r3: {x: 0.0, y: 6.0, Y: 0.0, topic: "local_map"}
    frontier:
      freq: 5.0
      plugin: easynav_frontier_maps_manager/FrontierMapsManager
      proximity_radius: 0.4 # Must be greater than system node position tolerance
      obstacle_threshold: 40
      clustering: true
      dbscan_eps_px: 0
      dbscan_min_points: 10

r2/planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [costmap]
    costmap:
      freq: 1.0
      plugin: easynav_costmap_planner/CostmapPlanner
      cost_factor: 10.0

r2/sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [laser1]
    perception_default_frame: odom
    laser1: {topic: scan_raw, type: sensor_msgs/msg/LaserScan}
    camera1: {topic: rgbd_camera/points, type: sensor_msgs/msg/PointCloud2}

r2/system_node:
  ros__parameters:
    use_sim_time: true
    use_real_time: false
    freq: 30.0
    rt_freq: 50.0
    allow_preempt_goal: true
    position_tolerance: 0.4
    angle_tolerance: 1.0
    tf_prefix: r2



r3/controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [simple]
    simple:
      rt_freq: 30.0 
      plugin: easynav_simple_controller/SimpleController
      max_linear_speed: 0.35
      max_angular_speed: 0.45
      look_ahead_dist: 0.3
      k_rot: 1.5
      k_p: 1.3
      k_i: 0.0
      k_d: 0.15

r3/localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [lazy]
    lazy:
      rt_freq: 30.0
      freq: 10.0
      plugin: easynav_lazy_localizer/LazyLocalizer

r3/maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [costmap, multiplexor, frontier]
    costmap:
      freq: 10.0
      plugin: easynav_costmap_maps_manager/CostmapMapsManager
      filters: [obstacles, inflation]
      obstacles:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/ObstaclesFilter
      inflation:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/InflationFilter
        inflation_radius: 1.0
        cost_scaling_factor: 8.0
        inscribed_radius: 0.05
    multiplexor:
      freq: 5.0
      plugin: easynav_multiplexor_maps_manager/MultiplexorMapsManager
      fixed_map_ns: "r3"
      robot_namespaces: ["r1", "r2", "r3"]
      r1: {x: 0.0, y: 0.0, Y: 0.0, topic: "local_map"}
      r2: {x: 0.0, y: -3.0, Y: 0.0, topic: "local_map"}
      r3: {x: 0.0, y: 6.0, Y: 0.0, topic: "local_map"}
    frontier:
      freq: 5.0
      plugin: easynav_frontier_maps_manager/FrontierMapsManager
      proximity_radius: 0.4 # Must be greater than system node position tolerance
      obstacle_threshold: 40
      clustering: true
      dbscan_eps_px: 0
      dbscan_min_points: 10

r3/planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [costmap]
    costmap:
      freq: 1.0
      plugin: easynav_costmap_planner/CostmapPlanner
      cost_factor: 10.0

r3/sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [laser1]
    perception_default_frame: odom
    laser1: {topic: scan_raw, type: sensor_msgs/msg/LaserScan}
    camera1: {topic: rgbd_camera/points, type: sensor_msgs/msg/PointCloud2}

r3/system_node:
  ros__parameters:
    use_sim_time: true
    use_real_time: false
    freq: 30.0
    rt_freq: 50.0
    allow_preempt_goal: true
    position_tolerance: 0.4
    angle_tolerance: 1.0
    tf_prefix: r3